# numpy 简介

## ndarray 数组

In [1]:
import numpy as np

### 一维数组

In [2]:
data = np.array([1,2,4,5])
data

array([1, 2, 4, 5])

In [3]:
data.shape

(4,)

In [4]:
data.dtype

dtype('int64')

In [5]:
data[0] = 9
data

array([9, 2, 4, 5])

### 二维数组

In [6]:
data = np.array([[1,2], [3,4]])
data

array([[1, 2],
       [3, 4]])

In [7]:
data[0,1]

2

In [8]:
data.shape

(2, 2)

### arange

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
data = np.arange(1, 10)
data

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### reshape

In [11]:
data2 = data.reshape(3,3)
data2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
data

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
data2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
data2[0,1] = 100

In [15]:
data2

array([[  1, 100,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [16]:
data

array([  1, 100,   3,   4,   5,   6,   7,   8,   9])

### 其他创建方法

In [17]:
np.zeros((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [18]:
a = np.ones((2,2,3))
a

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

In [19]:
a[0, 1, 2]

1.0

In [20]:
b = np.arange(12).reshape(2,2,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [21]:
b[0, 1, 2]

5

In [22]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [23]:
np.random.randint(1, 10, (3, 3))

array([[7, 7, 4],
       [3, 9, 8],
       [5, 1, 2]])

### 索引

In [24]:
# 一维数组
data = np.arange(100, step=10)
data

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [25]:
data[1:5]

array([10, 20, 30, 40])

In [26]:
data[4:]

array([40, 50, 60, 70, 80, 90])

In [27]:
data[:4]

array([ 0, 10, 20, 30])

In [28]:
# 二维数组
data = np.arange(16).reshape(4, 4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [29]:
data[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
data[1:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
data[:3]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
data[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [33]:
data[:, 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [34]:
data[2:4, :]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
data[2:5]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### 数组作为索引

In [36]:
data = np.arange(16).reshape(4,4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
data[[0, 2, 3], [1, 2, 3]]

array([ 1, 10, 15])

In [38]:
print data[0,1], data[2,2], data[3,3]

1 10 15


In [39]:
xidx = np.array([0, 2, 3])
yidx = np.array([1, 2, 3])
data[xidx, yidx]

array([ 1, 10, 15])

In [40]:
# 修改每行里的特定列的数据
yidx = [0, 3, 2, 0]
data[np.arange(4), yidx] += 100
data

array([[100,   1,   2,   3],
       [  4,   5,   6, 107],
       [  8,   9, 110,  11],
       [112,  13,  14,  15]])

### bool 索引

In [41]:
data = np.arange(16).reshape(4,4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [42]:
idx = data >= 10

In [43]:
idx

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [44]:
data[idx]

array([10, 11, 12, 13, 14, 15])

In [45]:
# 输出是元素线性化后的结果
data[data >= 10]

array([10, 11, 12, 13, 14, 15])

In [46]:
# 偶数元素
data[data % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

### 数学运算

In [47]:
x = np.arange(1,5).reshape(2,2)
x

array([[1, 2],
       [3, 4]])

In [48]:
y = np.arange(5,9).reshape(2,2)
y

array([[5, 6],
       [7, 8]])

In [49]:
x + y

array([[ 6,  8],
       [10, 12]])

In [50]:
np.add(x, y)

array([[ 6,  8],
       [10, 12]])

In [51]:
y - x

array([[4, 4],
       [4, 4]])

In [52]:
np.subtract(y, x)

array([[4, 4],
       [4, 4]])

In [53]:
x * y

array([[ 5, 12],
       [21, 32]])

In [54]:
x / y

array([[0, 0],
       [0, 0]])

In [55]:
x = np.array(x, dtype=float)
x

array([[ 1.,  2.],
       [ 3.,  4.]])

In [56]:
y = np.array(y, dtype=float)
y

array([[ 5.,  6.],
       [ 7.,  8.]])

In [57]:
x / y

array([[ 0.2       ,  0.33333333],
       [ 0.42857143,  0.5       ]])

In [58]:
np.sqrt(x)

array([[ 1.        ,  1.41421356],
       [ 1.73205081,  2.        ]])

In [59]:
x

array([[ 1.,  2.],
       [ 3.,  4.]])

In [60]:
x + 10

array([[ 11.,  12.],
       [ 13.,  14.]])

### 矩阵运算

In [61]:
a = np.array([[2,4], [3, 7]])
a

array([[2, 4],
       [3, 7]])

In [62]:
b = np.arange(4).reshape(2,2)
b

array([[0, 1],
       [2, 3]])

In [63]:
a.dot(b)

array([[ 8, 14],
       [14, 24]])

In [64]:
np.dot(a,b)

array([[ 8, 14],
       [14, 24]])

In [65]:
c = np.arange(6).reshape(2,3)
c

array([[0, 1, 2],
       [3, 4, 5]])

In [66]:
a.dot(c)

array([[12, 18, 24],
       [21, 31, 41]])

In [67]:
c.dot(a)

ValueError: objects are not aligned

In [68]:
c.T

array([[0, 3],
       [1, 4],
       [2, 5]])

### 统计功能

In [69]:
data = np.arange(16).reshape(4,4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [70]:
data.sum()

120

In [71]:
data.sum(axis=0)

array([24, 28, 32, 36])

In [72]:
data.sum(axis=1)

array([ 6, 22, 38, 54])

### 几个常用函数

In [73]:
np.linspace(0, 10, num=51)

array([  0. ,   0.2,   0.4,   0.6,   0.8,   1. ,   1.2,   1.4,   1.6,
         1.8,   2. ,   2.2,   2.4,   2.6,   2.8,   3. ,   3.2,   3.4,
         3.6,   3.8,   4. ,   4.2,   4.4,   4.6,   4.8,   5. ,   5.2,
         5.4,   5.6,   5.8,   6. ,   6.2,   6.4,   6.6,   6.8,   7. ,
         7.2,   7.4,   7.6,   7.8,   8. ,   8.2,   8.4,   8.6,   8.8,
         9. ,   9.2,   9.4,   9.6,   9.8,  10. ])