# numpy 简介

## ndarray 数组

In [2]:
import numpy as np

### 一维数组

In [33]:
data = np.array([1,2,4,5])
data

array([1, 2, 4, 5])

In [4]:
data.shape

(4,)

In [5]:
data.dtype

dtype('int32')

In [7]:
data[0] = 9
data

array([9, 2, 4, 5])

### 二维数组

In [12]:
data = np.array([[1,2], [3,4]])
data

array([[1, 2],
       [3, 4]])

In [13]:
data[0,1]

2

In [14]:
data.shape

(2, 2)

### arange

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
data = np.arange(1, 10)
data

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### reshape

In [36]:
data2 = data.reshape(3,3)
data2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
data

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
data2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
data2[0,1] = 100

In [40]:
data2

array([[  1, 100,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [41]:
data

array([  1, 100,   3,   4,   5,   6,   7,   8,   9])

### 其他创建方法

In [43]:
np.zeros((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [46]:
a = np.ones((2,2,3))
a

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

In [47]:
a[0, 1, 2]

1.0

In [48]:
b = np.arange(12).reshape(2,2,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [49]:
b[0, 1, 2]

5

In [55]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [57]:
np.random.randint(1, 10, (3, 3))

array([[9, 3, 9],
       [4, 1, 8],
       [2, 4, 6]])

### 索引

In [63]:
# 一维数组
data = np.arange(100, step=10)
data

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [64]:
data[1:5]

array([10, 20, 30, 40])

In [65]:
data[4:]

array([40, 50, 60, 70, 80, 90])

In [66]:
data[:4]

array([ 0, 10, 20, 30])

In [80]:
# 二维数组
data = np.arange(16).reshape(4, 4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [81]:
data[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [82]:
data[1:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [83]:
data[:3]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
data[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [85]:
data[:, 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [86]:
data[2:4, :]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [88]:
data[2:5]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### 数组作为索引

In [89]:
data = np.arange(16).reshape(4,4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [91]:
data[[0, 2, 3], [1, 2, 3]]

array([ 1, 10, 15])

In [95]:
print data[0,1], data[2,2], data[3,3]

1 10 15


In [97]:
xidx = np.array([0, 2, 3])
yidx = np.array([1, 2, 3])
data[xidx, yidx]

array([ 1, 10, 15])

In [99]:
# 修改每行里的特定列的数据
yidx = [0, 3, 2, 0]
data[np.arange(4), yidx] += 100
data

array([[100,   1,   2,   3],
       [  4,   5,   6, 107],
       [  8,   9, 110,  11],
       [112,  13,  14,  15]])

### bool 索引

In [100]:
data = np.arange(16).reshape(4,4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [101]:
idx = data >= 10

In [102]:
idx

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [103]:
data[idx]

array([10, 11, 12, 13, 14, 15])

In [106]:
# 输出是元素线性化后的结果
data[data >= 10]

array([10, 11, 12, 13, 14, 15])

In [108]:
# 偶数元素
data[data % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

### 数学运算

In [111]:
x = np.arange(1,5).reshape(2,2)
x

array([[1, 2],
       [3, 4]])

In [112]:
y = np.arange(5,9).reshape(2,2)
y

array([[5, 6],
       [7, 8]])

In [113]:
x + y

array([[ 6,  8],
       [10, 12]])

In [115]:
np.add(x, y)

array([[ 6,  8],
       [10, 12]])

In [116]:
y - x

array([[4, 4],
       [4, 4]])

In [117]:
np.subtract(y, x)

array([[4, 4],
       [4, 4]])

In [118]:
x * y

array([[ 5, 12],
       [21, 32]])

In [119]:
x / y

array([[0, 0],
       [0, 0]])

In [122]:
x = np.array(x, dtype=float)
x

array([[ 1.,  2.],
       [ 3.,  4.]])

In [123]:
y = np.array(y, dtype=float)
y

array([[ 5.,  6.],
       [ 7.,  8.]])

In [124]:
x / y

array([[ 0.2       ,  0.33333333],
       [ 0.42857143,  0.5       ]])

In [125]:
np.sqrt(x)

array([[ 1.        ,  1.41421356],
       [ 1.73205081,  2.        ]])

In [141]:
x

array([[ 1.,  2.],
       [ 3.,  4.]])

In [142]:
x + 10

array([[ 11.,  12.],
       [ 13.,  14.]])

### 矩阵运算

In [126]:
a = np.array([[2,4], [3, 7]])
a

array([[2, 4],
       [3, 7]])

In [127]:
b = np.arange(4).reshape(2,2)
b

array([[0, 1],
       [2, 3]])

In [128]:
a.dot(b)

array([[ 8, 14],
       [14, 24]])

In [129]:
np.dot(a,b)

array([[ 8, 14],
       [14, 24]])

In [131]:
c = np.arange(6).reshape(2,3)
c

array([[0, 1, 2],
       [3, 4, 5]])

In [132]:
a.dot(c)

array([[12, 18, 24],
       [21, 31, 41]])

In [133]:
c.dot(a)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [139]:
c.T

array([[0, 3],
       [1, 4],
       [2, 5]])

### 统计功能

In [134]:
data = np.arange(16).reshape(4,4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [136]:
data.sum()

120

In [137]:
data.sum(axis=0)

array([24, 28, 32, 36])

In [138]:
data.sum(axis=1)

array([ 6, 22, 38, 54])

### 几个常用函数

In [146]:
np.linspace(0, 10, num=51)

array([  0. ,   0.2,   0.4,   0.6,   0.8,   1. ,   1.2,   1.4,   1.6,
         1.8,   2. ,   2.2,   2.4,   2.6,   2.8,   3. ,   3.2,   3.4,
         3.6,   3.8,   4. ,   4.2,   4.4,   4.6,   4.8,   5. ,   5.2,
         5.4,   5.6,   5.8,   6. ,   6.2,   6.4,   6.6,   6.8,   7. ,
         7.2,   7.4,   7.6,   7.8,   8. ,   8.2,   8.4,   8.6,   8.8,
         9. ,   9.2,   9.4,   9.6,   9.8,  10. ])